version: "3"

services:
  localstack:
    image: localstack/localstack
    container_name: java-vertx-4-localstack
    #    restart: always
    ports:
      - "4566:4566"
    environment:
      - AWS_DEFAULT_REGION=ap-southeast-1
      - EDGE_PORT=4566
      - SERVICES=dynamodb
      - DATA_DIR=/tmp/localstack/data

    volumes:
      - java-vertx-4-datavolume:/tmp/localstack

  master:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://master:8089

  worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master

  redis-master:
    container_name: java-vertx-4-redis-master
    image: redis
    volumes:
      - java-vertx-4-datavolume:/data
    ports:
      - 9379:6379

  redis-slave-1:
    container_name: java-vertx-4-redis-slave
    image: redis
    ports:
      - 19379:6379
    volumes:
      - java-vertx-4-datavolume:/data
    command: redis-server --slaveof redis-master 6379

  dynamodb-admin:
    depends_on:
      - localstack
    image: aaronshaf/dynamodb-admin
    container_name: java-vertx-4-dynamodb
    #    restart: always
    ports:
      - 9020:8001
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566

volumes:
  java-vertx-4-datavolume:
